import { Post } from "@/components/post-card"
import { User } from "@/components/user-card"

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Marie Laurent",
    username: "marielaurent",
    avatar: null,
    initials: "ML",
    bio: "Designer passionnée par l'UX et les interfaces épurées. Basée à Paris.",
    followers: 2450,
    isFriend: false,
  },
  {
    id: "2",
    name: "Thomas Bernard",
    username: "thomasb",
    avatar: null,
    initials: "TB",
    bio: "Développeur full-stack et amateur de café. Je partage mes découvertes tech.",
    followers: 1280,
    isFriend: true,
  },
  {
    id: "3",
    name: "Sophie Martin",
    username: "sophiem",
    avatar: null,
    initials: "SM",
    bio: "Photographe de rue et voyageuse. Capturer l'instant présent.",
    followers: 5800,
    isFriend: false,
  },
  {
    id: "4",
    name: "Lucas Dubois",
    username: "lucasd",
    avatar: null,
    initials: "LD",
    bio: "Entrepreneur et passionné d'innovation. Fondateur de StartupX.",
    followers: 3200,
    isFriend: true,
  },
  {
    id: "5",
    name: "Emma Petit",
    username: "emmapetit",
    avatar: null,
    initials: "EP",
    bio: "Autrice et blogueuse. J'écris sur la vie quotidienne et la créativité.",
    followers: 890,
    isFriend: false,
  },
]

export const mockPosts: Post[] = [
  {
    id: "1",
    author: mockUsers[0],
    title: "Les principes du design minimaliste",
    content: "Le minimalisme n'est pas simplement une question d'esthétique, c'est une philosophie de conception qui met l'accent sur l'essentiel. Voici les principes que j'applique dans chacun de mes projets pour créer des interfaces claires et efficaces.",
    image: "/images/chris-lee-70l1tDAI6rM-unsplash.jpg",
    likes: 128,
    comments: 24,
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    isLiked: false,
    isSaved: false,
  },
  {
    id: "2",
    author: mockUsers[1],
    title: "Découverte de Next.js 16",
    content: "J'ai enfin eu le temps de tester les nouvelles fonctionnalités de Next.js 16, notamment les Cache Components et le support amélioré de React 19. Le nouveau système de cache avec 'use cache' change vraiment la donne pour les performances.",
    likes: 256,
    comments: 42,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    isLiked: true,
    isSaved: true,
  },
  {
    id: "3",
    author: mockUsers[2],
    title: "Lever de soleil sur Montmartre",
    content: "Ce matin, j'ai capturé ce moment magique à Montmartre. La lumière dorée qui enveloppe les toits de Paris est simplement incroyable. Ces instants me rappellent pourquoi j'aime tant cette ville.",
    image: "/images/hoang-mai-nguyen-QNTXk3lCnlA-unsplash.jpg",
    likes: 482,
    comments: 56,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    isLiked: false,
    isSaved: false,
  },
  {
    id: "4",
    author: mockUsers[3],
    title: "Comment valider une idée de startup",
    content: "Après avoir lancé trois entreprises, voici ma méthode pour valider une idée avant d'investir du temps et de l'argent. L'essentiel est de parler à vos futurs utilisateurs le plus tôt possible et de construire un MVP en quelques semaines, pas en quelques mois.",
    likes: 198,
    comments: 38,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    isLiked: false,
    isSaved: true,
  },
  {
    id: "5",
    author: mockUsers[4],
    title: "L'art de la routine créative",
    content: "Beaucoup pensent que la créativité est spontanée, mais je trouve qu'elle se cultive avec des rituels quotidiens. Écrire chaque matin, même 10 minutes, a transformé ma productivité et la qualité de mes idées.",
    image: "/images/jeremy-cai-ucYWe5mzTMU-unsplash.jpg",
    likes: 94,
    comments: 18,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    isLiked: false,
    isSaved: false,
  },
  {
    id: "6",
    author: mockUsers[0],
    title: "",
    content: "Petite réflexion du jour : un bon design est invisible. Si l'utilisateur remarque le design, c'est que quelque chose ne fonctionne pas comme il devrait. L'objectif est toujours de faciliter l'expérience, pas de la décorer.",
    likes: 76,
    comments: 12,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    isLiked: true,
    isSaved: false,
  },
]

export const trendingTopics = [
  { tag: "#Design", posts: 1250 },
  { tag: "#Tech", posts: 980 },
  { tag: "#Startup", posts: 756 },
  { tag: "#Photography", posts: 623 },
  { tag: "#Créativité", posts: 512 },
]

export const notifications = [
  {
    id: "1",
    type: "like" as const,
    user: mockUsers[1],
    post: mockPosts[0],
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    read: false,
  },
  {
    id: "2",
    type: "comment" as const,
    user: mockUsers[2],
    post: mockPosts[0],
    message: "Superbe article ! J'adore ton approche du minimalisme.",
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    read: false,
  },
  {
    id: "3",
    type: "friend_request" as const,
    user: mockUsers[4],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    read: true,
  },
]
